// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUqtZjKeVV0AvPTT58nY-mhI-qH1XCupg',
    appId: '1:87806078033:web:36ab48c659343e53759c70',
    messagingSenderId: '87806078033',
    projectId: 'assignment-25a2e',
    authDomain: 'assignment-25a2e.firebaseapp.com',
    storageBucket: 'assignment-25a2e.appspot.com',
    measurementId: 'G-7KBPPXLFZ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv0S9hOjj8OzAT1yCfL28mpaBKuJ9BvkU',
    appId: '1:87806078033:android:9310d27239a3f509759c70',
    messagingSenderId: '87806078033',
    projectId: 'assignment-25a2e',
    storageBucket: 'assignment-25a2e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeOcuKaQUtmLc1Zo6hnTVVtK0b_PojxpI',
    appId: '1:87806078033:ios:285b668b9e424b46759c70',
    messagingSenderId: '87806078033',
    projectId: 'assignment-25a2e',
    storageBucket: 'assignment-25a2e.appspot.com',
    iosBundleId: 'com.example.assignmentTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeOcuKaQUtmLc1Zo6hnTVVtK0b_PojxpI',
    appId: '1:87806078033:ios:285b668b9e424b46759c70',
    messagingSenderId: '87806078033',
    projectId: 'assignment-25a2e',
    storageBucket: 'assignment-25a2e.appspot.com',
    iosBundleId: 'com.example.assignmentTest',
  );
}
